name: latexmk
on:
  push:
jobs:
  latexmk:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: yegor256/latexmk-action@0.12.0
        with:
          cmd: latexmk
          path: foo
          opts: -pdf